<a href="https://colab.research.google.com/github/furkanoruc/IntroDL/blob/main/Stride_Stochastic_Batch_Gradient_Descent_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1

In [2]:
a = np.array([[0,1,2,3,4,5,6], [0,1,2,3,4,5,6], [0,1,2,3,4,5,6],
              [0,1,2,3,4,5,6], [0,1,2,3,4,5,6], [0,1,2,3,4,5,6],
              [0,1,2,3,4,5,6]])
print(a)

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


# 2

In [67]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11], dtype=np.int32)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
arr.strides

(4,)

In [95]:
arr_strided = np.lib.stride_tricks.as_strided(arr, shape = (len(arr)-3,4), strides = (4,4))
print(arr_strided)

[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]


# 3

To perform updates, batch gradient descent considers the entire sample set, while stochastic gradient descent conducts update for each distinct data point. In stochastic gradient descent, we approach the approximated gradient descent rather than the exact. Finding exact requires much more time since each update of the gradient descent requires going over the entire dataset (batch). Mini Batch gradient descent stands as the mid point methodology, where positive and negative aspects of both approaches are adopted.